# Generated by Django 2.0.4 on 2018-04-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0003_book_related'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('bookname',)},
        ),
    ]
