# Generated by Django 2.0.4 on 2018-04-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0004_auto_20180429_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
