# Generated by Django 2.0.4 on 2018-05-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0005_auto_20180429_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_book_related_+', to='book_management.Book'),
        ),
    ]
