# Generated by Django 2.0.5 on 2018-05-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0007_auto_20180507_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picbook',
            field=models.ImageField(blank=True, null=True, upload_to='book_image'),
        ),
    ]
